version: "3"

networks:
  kafka_net:
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    user: root
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - /root/DockerContainers/zookeeper/data:/bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka_net

  kafka:
    hostname: 192.168.99.100
    image: bitnami/kafka:latest
    user: root
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - /root/DockerContainers/kafka/data:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - kafka_net

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local